export const targetCompanies = [
    { label: "Accenture", value: "accenture", icon: "/images/icons/accenture.svg" },
    { label: "Adobe", value: "adobe", icon: "/images/icons/adobe.svg" },
    { label: "Airbnb", value: "airbnb", icon: "/images/icons/airbnb.svg" },
    { label: "Amazon", value: "amazon", icon: "/images/icons/amazon.svg" },
    { label: "American Airlines", value: "american-airlines", icon: "/images/icons/aa.svg" },
    { label: "American Express", value: "american-express", icon: "/images/icons/american-express.svg" },
    { label: "Apple", value: "apple", icon: "/images/icons/apple.svg"},
    { label: "AT&T", value: "att", icon: "/images/icons/AT&T.svg" },
    { label: "Bank of America", value: "bank-of-america", icon: "/images/icons/boa.svg" },
    { label: "Best Buy", value: "best-buy", icon: "/images/icons/best-buy.svg" },
    { label: "Boeing", value: "boeing", icon: "/images/icons/boeing.svg" },
    { label: "Booz Allen Hamilton", value: "booz-allen-hamilton", icon: "/images/icons/bah.svg" },
    { label: "Capital One", value: "capital-one", icon: "/images/icons/capital-one.svg" },
    { label: "Cisco", value: "cisco", icon: "/images/icons/cisco.svg" },
    { label: "Coca-Cola", value: "coca-cola", icon: "/images/icons/cc.svg" },
    { label: "Comcast", value: "comcast", icon: "/images/icons/comcast.svg" },
    { label: "Costco", value: "costco", icon: "/images/icons/costco.svg" },
    { label: "CVS Health", value: "cvs-health", icon: "/images/icons/cvs.svg" },
    { label: "Deloitte", value: "deloitte", icon: "/images/icons/deloitte.svg" },
    { label: "Delta Air Lines", value: "delta-air-lines", icon: "/images/icons/delta.svg" },
    { label: "DoorDash", value: "doordash", icon: "/images/icons/dd.svg" },
    { label: "FedEx", value: "fedex", icon: "/images/icons/fdx.svg" },
    { label: "General Electric", value: "general-electric", icon: "/images/icons/ge.svg" },
    { label: "General Motors", value: "general-motors", icon: "/images/icons/gm.svg" },
    { label: "Goldman Sachs", value: "goldman-sachs", icon: "/images/icons/gs.svg" },
    { label: "Google", value: "google", icon: "/images/icons/google.svg" },
    { label: "IBM", value: "ibm", icon: "/images/icons/ibm.svg" },
    { label: "Intel", value: "intel", icon: "/images/icons/intel.svg" },
    { label: "KPMG", value: "kpmg", icon: "/images/icons/kpmg.svg" },
    { label: "Lockheed Martin", value: "lockheed-martin", icon: "/images/icons/lt.svg" },
    { label: "Lowe's", value: "lowes", icon: "/images/icons/lowes.svg" },
    { label: "Meta", value: "meta", icon: "/images/icons/meta.svg" },
    { label: "Microsoft", value: "microsoft", icon: "/images/icons/ms.svg" },
    { label: "Netflix", value: "netflix", icon: "/images/icons/nf.svg" },
    { label: "Nike", value: "nike", icon: "/images/icons/nike.svg" },
    { label: "NVIDIA", value: "nvidia", icon: "/images/icons/nv.svg" },
    { label: "Oracle", value: "oracle", icon: "/images/icons/or.svg" },
    { label: "Pfizer", value: "pfizer", icon: "/images/icons/pf.svg" },
    { label: "PwC", value: "pwc", icon: "/images/icons/pwc.svg" },
    { label: "Shopify", value: "shopify", icon: "/images/icons/shop.svg" },
    { label: "Starbucks", value: "starbucks", icon: "/images/icons/sb.svg" },
    { label: "Target", value: "target", icon: "/images/icons/tar.svg" },
    { label: "Tesla", value: "tesla", icon: "/images/icons/tes.svg" },
    { label: "The Walt Disney Company", value: "the-walt-disney-company", icon: "/images/icons/dis.svg" },
    { label: "T-Mobile", value: "t-mobile", icon: "/images/icons/tm.svg" },
    { label: "Uber", value: "uber", icon: "/images/icons/ub.svg" },
    { label: "United Airlines", value: "united-airlines", icon: "/images/icons/ua.svg" },
    { label: "UPS", value: "ups", icon: "/images/icons/ups.svg" },
    { label: "Verizon", value: "verizon", icon: "/images/icons/vz.svg" },
    { label: "Visa", value: "visa", icon: "/images/icons/v.svg" },
    { label: "Walgreens", value: "walgreens", icon: "/images/icons/wg.svg" },
    { label: "Walmart", value: "walmart", icon: "/images/icons/wm.svg" },
    { label: "Wells Fargo", value: "wells-fargo", icon: "/images/icons/wf.svg" },
    { label: "Other", value: "other" },
];